In [1]:
from torch import distributions
import torch


fake_prob_dist = distributions.beta.Beta(0.5, 0.5)

In [4]:
fake_input_tensor = torch.rand((2, 5))
print(fake_input_tensor)
real_input_tensor = torch.rand((2, 5))
print(real_input_tensor)
target_fake_prob = fake_prob_dist.sample((len(fake_input_tensor),)).float()
print(target_fake_prob)
fake_weight = target_fake_prob.view(-1, 1, 1, 1)
print(fake_weight)
# input_tensor = (1.0 - fake_weight) * real_input_tensor + fake_weight * fake_input_tensor
# print(input_tensor)

tensor([[0.1192, 0.1206, 0.4796, 0.5762, 0.3899],
        [0.8289, 0.1624, 0.3562, 0.9830, 0.8234]])
tensor([[0.5382, 0.5591, 0.7896, 0.2217, 0.1199],
        [0.8993, 0.9941, 0.1499, 0.4722, 0.6949]])
tensor([0.0220, 0.8680])
tensor([[[[0.0220]]],


        [[[0.8680]]]])


In [6]:
import numpy as np

In [9]:
tensor1 = torch.sigmoid(torch.rand((1, 10)))
tensor2 = torch.sigmoid(torch.rand((1, 10)))

In [10]:
print(tensor1)
print(tensor2)

tensor([[0.6566, 0.6906, 0.5232, 0.6231, 0.7197, 0.6388, 0.6667, 0.5950, 0.7173,
         0.6610]])
tensor([[0.7013, 0.6611, 0.7196, 0.6838, 0.6861, 0.6124, 0.6861, 0.6935, 0.6404,
         0.7109]])


In [11]:
t3 = np.concatenate((tensor1, tensor2))

In [12]:
t3 = 

array([[0.65662885, 0.6906211 , 0.5232415 , 0.623069  , 0.71965355,
        0.63878894, 0.6666758 , 0.5950329 , 0.7172568 , 0.66101736],
       [0.7013289 , 0.66114527, 0.7196466 , 0.6837676 , 0.68614525,
        0.6123561 , 0.6861016 , 0.6935068 , 0.6403562 , 0.71094227]],
      dtype=float32)

In [13]:
delta = t3 - 0.5

In [14]:
delta

array([[0.15662885, 0.19062108, 0.02324152, 0.12306899, 0.21965355,
        0.13878894, 0.1666758 , 0.09503287, 0.21725678, 0.16101736],
       [0.20132887, 0.16114527, 0.21964657, 0.18376762, 0.18614525,
        0.11235613, 0.18610162, 0.19350678, 0.14035618, 0.21094227]],
      dtype=float32)

In [15]:
sign = np.sign(delta)

In [16]:
sign

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [17]:
pos_delta = delta > 0
neg_delta = delta < 0

In [18]:
pos_delta

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [19]:
neg_delta

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [20]:
t3[pos_delta] = np.clip(0.5 + sign[pos_delta] * np.power(abs(delta[pos_delta]), 0.65), 0.01, 0.99)
t3[neg_delta] = np.clip(0.5 + sign[neg_delta] * np.power(abs(delta[neg_delta]), 0.65), 0.01, 0.99)

In [21]:
t3

array([[0.79968613, 0.8404953 , 0.5867106 , 0.7562103 , 0.87336177,
        0.7770325 , 0.812045  , 0.71657985, 0.8707086 , 0.8051176 ],
       [0.8528085 , 0.80527514, 0.8733541 , 0.8324871 , 0.835277  ,
        0.74148375, 0.83522594, 0.8438369 , 0.7790619 , 0.86366904]],
      dtype=float32)

In [22]:
t3[pos_delta]

array([0.79968613, 0.8404953 , 0.5867106 , 0.7562103 , 0.87336177,
       0.7770325 , 0.812045  , 0.71657985, 0.8707086 , 0.8051176 ,
       0.8528085 , 0.80527514, 0.8733541 , 0.8324871 , 0.835277  ,
       0.74148375, 0.83522594, 0.8438369 , 0.7790619 , 0.86366904],
      dtype=float32)

In [23]:
t3[neg_delta]

array([], dtype=float32)

In [24]:
weights = np.power(abs(delta), 1.0) + 1e-4

In [25]:
weights

array([[0.15672885, 0.19072108, 0.02334152, 0.12316899, 0.21975355,
        0.13888894, 0.16677581, 0.09513287, 0.21735679, 0.16111736],
       [0.20142888, 0.16124527, 0.21974657, 0.18386762, 0.18624525,
        0.11245613, 0.18620162, 0.19360678, 0.14045618, 0.21104227]],
      dtype=float32)

In [26]:
video_score = float((t3 * weights).sum() / weights.sum())

In [27]:
video_score

0.8242036700248718

In [28]:
weights.sum()

3.289282

In [29]:
(t3 * weights).sum()

2.7110384

In [3]:
import numpy as np

In [4]:
list_example = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

In [5]:
a = np.array(list_example)

In [6]:
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [7]:
a - 0.5

array([-0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5])

In [5]:
import logging

In [7]:
history = {
    "train":[1,2,3],
    "val":[2,3,5]
}

In [8]:
logging.info(history)